version: '3'
services:
  hellper_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "hellper"
      POSTGRES_PASSWORD: "hellper"
      POSTGRES_DB: "hellper"
    ports:
      - "5432:5432"
    networks:
      - hellper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellper"]
      interval: 10s
      timeout: 5s
      retries: 5

  hellper:
    image: golang:1.13
    volumes:
      - .:/app/hellper
    working_dir: /app/hellper
    command: go run ./cmd/http -v
    env_file:
      - development.env
    ports:
      - "8080:8080"
    depends_on:
      hellper_db:
        condition: service_healthy
    networks:
      - hellper

networks:
    hellper:
