version: '3'
services:
  hellper_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "hellper_dev"
      POSTGRES_PASSWORD: "hellper_dev"
      POSTGRES_DB: "hellper_dev"
    ports:
      - "5432:5432"
    volumes:
      - ./internal/model/sql/postgres/schema:/docker-entrypoint-initdb.d
  hellper:
    image: golang:1.13
    volumes:
      - .:/app/hellper
    working_dir: /app/hellper
    command: go run ./cmd/http -v
    env_file:
      - development.env
    ports:
      - "8080:8080"
    depends_on:
      - hellper_db
networks:
  default:
    driver: bridge


